spring.application.name=energypulse-core
server.port=${SERVER_PORT:8080}

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:energypulse}
spring.datasource.username=${POSTGRES_USER:energypulse}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.sql.init.mode=never

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized


# Apache Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
app.kafka.topics.home-registration=${KAFKA_REGISTRATION_TOPIC:energypulse.home-registration.v1}
app.kafka.topics.telemetry=${KAFKA_TELEMETRY_TOPIC:energypulse.telemetry.v1}

# Apache Ignite
app.ignite.addresses=${IGNITE_ADDRESSES:localhost:10800}

# OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Web integration
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}